name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install check
      run: sudo apt install check
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: make test
